language: bash
services: docker

env:
  - VERSION=5 VARIANT=cli
  - VERSION=5 VARIANT=cli-dev
  - VERSION=5 VARIANT=fpm
  - VERSION=5 VARIANT=fpm-dev
  - VERSION=7 VARIANT=cli
  - VERSION=7 VARIANT=cli-dev
  - VERSION=7 VARIANT=fpm
  - VERSION=7 VARIANT=fpm-dev

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="php:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT}"
  - ~/official-images/test/run.sh "$image"
  - if [[ $VARIANT =~ ^....dev ]] ; then docker run -it --rm $image git --version ; fi

after_script:
  - docker images

# vim:set et ts=2 sw=2:i
